### ISSUE TITLE
Filter changes the Redux state

### ISSUE THREAD

**Issue by KateKate** [michaelcontento/redux-storage-decorator-filter#13]
Hi! Thank you for your lib. It's really helpful.
Found one issue with that line:
```
if (whitelist.length === 0 && blacklist.length > 0) {
                saveState = { ...state };
            }
```
If you have the deep state, the filter will change the state itself. So it's better to replace with:
```
saveState = cloneDeep(state);
```
If it looks good for you I could send PR.
Thanks in advance!

**Comment by michaelcontento** [comment]
fixed fb1416b
