### ISSUE TITLE
Warning about using iterable.length instead of iterable.size with immutablejs

### ISSUE THREAD

**Issue by qingweibinary** [michaelcontento/redux-storage-decorator-filter#15]
I am using this awesome library in my company project, and I am having this issue.

<img width="1002" alt="screen shot 2016-03-15 at 11 25 38 am" src="https://cloud.githubusercontent.com/assets/14971922/13766913/e39f2490-eaa0-11e5-8f0d-d99e27c0f530.png">

Do you have any idea how to get rid of it?

It seems to be triggered from debounce and filter plugin

**Comment by borisyankov** [comment]
It is an issue with blacklist not handling immutable in any specific way.
It still seems to work, but the warning is not pleasant :)
