### ISSUE TITLE
an empty array for black list keys causes storage to not remember anything after refresh

### ISSUE THREAD

**Issue by faceyspacey** [michaelcontento/redux-storage-decorator-filter#38]
eg: `filter(createEngine('appstate'), null, [])`

will in fact breakdown whereas this will work:
`filter(createEngine('appstate'), null, ['FOO'])`

It's an extremely small issue, but something that will happen if you set up filtering with the plan that only later you will add such keys.

**Comment by michaelcontento** [comment]
Sorry for the late response.
And sorry to bring you bad news, but my focus has left the node / react ecosystem and this package is no longer maintained 😞

**Comment by michaelcontento** [comment]
Re-opened as @guns2410 want's to work on this project: Give him a warm welcome 👏

**Comment by guns2410** [comment]
Thanks @michaelcontento 

@faceyspacey filter expects either whitelist keys or blacklist keys to filter the state.

if none are specified an empty state is returned. have a look at the test [here](https://github.com/michaelcontento/redux-storage-decorator-filter/blob/master/src/__tests__/index-test.js#L15).

I would like to understand your use case for making this library flexible enough.

**Comment by faceyspacey** [comment]
It's been a while and I can't quite understand what the test case has to do with it, but the use case is when you're working on your project and at one point you decide you don't want any filters, but you want to leave an empty array as a reminder for the future or for whatever reason. So you leave the empty array and things fall apart and you have no idea why. It's a small edge case and likely small to fix. I meant to fix it myself, but just never go around to it. 

But basically, you can't leave an empty array. Give it a try. It will break down. It works if you don't provide the array or at least fill it with one value.

**Comment by guns2410** [comment]
Thanks @faceyspacey I will have a workaround on this today!

**Comment by michaelcontento** [comment]
Closed as PR #49 has been merged
