### ISSUE TITLE
Please confirm behavior of the filter

### ISSUE THREAD

**Issue by rturk** [michaelcontento/redux-storage-decorator-filter#4]
Hi @michaelcontento thanks for building and sharing this code. This looks great.

Can you please confirm the behavior of the state tree for items that are filtered? 
I'm using the load function right after my redux store function, so I'm assuming that items not saved will default to initial state, correct?

Let's say I just want to store `user` information and leave the rest of my tree out of the store procedure. Upon load (assuming that I'm calling load right after store) my new tree will contain the `user` information from disk and the rest of the tree will default to initialState.

**Comment by michaelcontento** [comment]
You're welcome! :smile: 

Yes, your right. [redux-storage](https://github.com/michaelcontento/redux-storage) will merge the current state with the loaded one and with a active filter, only partial objects get saved to disk. We're currently splitting out the merger function from redux-storage into own packages so it's trivial to write a custom one if you have too. The current default merger is [redux-storage-merger-simple](https://github.com/michaelcontento/redux-storage-merger-simple) and [in the tests](https://github.com/michaelcontento/redux-storage-merger-simple/blob/master/src/__tests__/index-test.js) you can quickly see how things get merged. 

Back to your specific case:
- initial state: `{ user: { name: null, randomNumber: null }, session: { id: null } }` 
- whitelist: `[ ['user', 'name'], 'session' ]`
- state before save: `{ user: { name: 'rturk', randomNumber: 42 }, session: { id: '1234' } }`  
- state after load: `{ user: { name: 'rturk', randomNumber: null }, session: { id: '1234' } }`
